on:
  release:
    types: [created]
permissions:
  contents: write
jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: mips-unknown-linux-musl
            archive: tar.gz
    steps:
      - uses: actions/checkout@master
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rust-src
      - name: Install MIPS cross-compilation tools
        run: sudo apt-get update && sudo apt-get install -y gcc-mips-linux-gnu libc6-dev-mips-cross
      - name: Build for MIPS
        run: |
          cargo +nightly build -Z build-std --target mips-unknown-linux-musl
        env:
          CC_mips_unknown_linux_musl: mips-linux-gnu-gcc
          CARGO_TARGET_MIPS_UNKNOWN_LINUX_MUSL_LINKER: mips-linux-gnu-gcc
